export const POSTGRES_PROVIDER_TOKEN: string = 'POSTGRES_PROVIDER';
export const USERS_REPOSITORY_TOKEN: string = 'USERS_REPOSITORY';
export const PROFILES_REPOSITORY_TOKEN: string = 'PROFILES_REPOSITORY';