export const USERS_REPOSITORY_TOKEN: string = 'USERS_REPOSITORY';
//export const PHOTOS_REPOSITORY_TOKEN: string = 'PHOTOS_REPOSITORY';
export const POSTGRES_PROVIDER_TOKEN: string = 'POSTGRES_PROVIDER';